# Generated by Django 5.1.1 on 2024-10-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_featured_image_project_vote_ratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('up', 'За'), ('down', 'Против')], max_length=10),
        ),
    ]
